// Auto-generated by build.rs — do not edit manually.
// Regenerate by building with the `bundled-schemas` feature.

//! Build-time embedded schemas with gzip compression.
//!
//! This module is auto-generated by `build.rs`. When the `bundled-schemas`
//! feature is enabled, schema JSON files from `schemas/database/` are
//! compressed at build time and embedded into the binary.

/// Embedded compressed schemas generated by `build.rs`.
///
/// Each entry is `(command_name, gzip_compressed_json_bytes)`.
pub const BUNDLED_SCHEMAS: &[(&str, &[u8])] = &[
];

/// Decompresses and parses all bundled schemas.
///
/// # Errors
///
/// Returns [`DatabaseError::CompressionError`](crate::DatabaseError::CompressionError)
/// if decompression fails, or
/// [`DatabaseError::JsonError`](crate::DatabaseError::JsonError)
/// if the decompressed data is not valid schema JSON.
pub fn load_bundled_schemas() -> crate::error::Result<Vec<command_schema_core::CommandSchema>> {
    use flate2::read::GzDecoder;
    use std::io::Read;

    let mut schemas = Vec::with_capacity(BUNDLED_SCHEMAS.len());

    for (name, compressed) in BUNDLED_SCHEMAS {
        let mut decoder = GzDecoder::new(*compressed);
        let mut json = String::new();
        decoder.read_to_string(&mut json).map_err(|e| {
            crate::DatabaseError::CompressionError(format!(
                "failed to decompress schema for {name}: {e}"
            ))
        })?;

        let schema: command_schema_core::CommandSchema = serde_json::from_str(&json)?;
        schemas.push(schema);
    }

    Ok(schemas)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_bundled() {
        let schemas = load_bundled_schemas().unwrap();
        assert_eq!(schemas.len(), 0);
    }

    #[test]
    fn test_compression_roundtrip() {
        use flate2::read::GzDecoder;
        use flate2::write::GzEncoder;
        use flate2::Compression;
        use std::io::{Read, Write};

        let schema = command_schema_core::CommandSchema::new(
            "test-cmd",
            command_schema_core::SchemaSource::Bootstrap,
        );
        let json = serde_json::to_string(&schema).unwrap();

        let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(json.as_bytes()).unwrap();
        let compressed = encoder.finish().unwrap();

        let mut decoder = GzDecoder::new(compressed.as_slice());
        let mut decompressed = String::new();
        decoder.read_to_string(&mut decompressed).unwrap();

        let parsed: command_schema_core::CommandSchema =
            serde_json::from_str(&decompressed).unwrap();
        assert_eq!(parsed.command, "test-cmd");
    }
}
